CREATE TABLE TREE(id IDENTITY PRIMARY KEY,  name VARCHAR(20));
CREATE TABLE BRANCH(id IDENTITY PRIMARY KEY,  name VARCHAR(20), tree_id BIGINT REFERENCES TREE(ID));
CREATE TABLE LEAF(id IDENTITY PRIMARY KEY,  name VARCHAR(20), branch_id BIGINT REFERENCES BRANCH(ID));